// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMgMrEkKurvBEh2iaIGCl-mPWAh5rRGtM',
    appId: '1:819592355905:web:effff25c957f2a099766c0',
    messagingSenderId: '819592355905',
    projectId: 'dominic-fitness-app',
    authDomain: 'dominic-fitness-app.firebaseapp.com',
    storageBucket: 'dominic-fitness-app.appspot.com',
    measurementId: 'G-WX2M7WDY2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwq9KJ6l8X_I-4uUuv0j-KERHymiZbRaA',
    appId: '1:819592355905:android:78fd786cd2d650949766c0',
    messagingSenderId: '819592355905',
    projectId: 'dominic-fitness-app',
    storageBucket: 'dominic-fitness-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6jsbPzRakoN4m_DxLVuZuC3jgijkAiU',
    appId: '1:819592355905:ios:56a02e0f6f8b3ccc9766c0',
    messagingSenderId: '819592355905',
    projectId: 'dominic-fitness-app',
    storageBucket: 'dominic-fitness-app.appspot.com',
    iosBundleId: 'dev.flutter.fitnessApp',
  );
}
